apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tasks
spec:
  replicas: 3
  selector:
    matchLabels:
      name: api-tasks
  template:
    metadata:
      labels:
        name: api-tasks
    spec:
      containers:
      - name: application
        image: api-tasks:1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000