version: "3.8"
services:

  db:
    image: mysql:8.0
    container_name: api-tasks
    restart: always
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata:
